swagger: '2.0'
info:
  title: Polls Swagger
  description: Polls is a simple API allowing consumers to view polls and vote in them.
  version: "8234aab51481d37a30757d925b7f4221a659427e"
host: polls.apiblueprint.org
schemes:
  - https
paths:
  /questions:
    x-summary: Questions Collection
    x-description: ''
    get:
      summary: List all questions
      responses:
        200:
          description: 'List'
          examples:
            application/json:
              - question: "Favourite programming language?"
                published_at: "2015-08-05T08:40:51.620Z"
                choices:
                  - choice: "Swift"
                    votes: 2048
                  - choice: "Python"
                    votes: 1024
                  - choice: "Objective-C"
                    votes: 512
                  - choice: "Ruby"
                    votes: 256
    post:
      summary: Create a New Question
      description: You may create your own question using this action. It takes a JSON object containing a question and a collection of answers in the form of choices.
      responses:
        201:
          description: 'Created'
          examples:
            application/json:
              question: "Favourite programming language?"
              published_at: "2014-11-11T08:40:51.620Z"
              choices:
                - choice: "Swift"
                  votes: 0
                - choice: "Python"
                  votes: 0
                - choice: "Objective-C"
                  votes: 0
                - choice: "Ruby"
                  votes: 0